CREATE TABLE [dbo].[Counties](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](100) NULL,
	[OstanId] [int] NOT NULL,
	[AmarCode] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY], 
    CONSTRAINT [PK_Counties] PRIMARY KEY ([Id])
) ON [PRIMARY]
GO
