CREATE TABLE [dbo].[Districts](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](100) NULL,
	[ProvinceId] [int] NOT NULL,
	[CountyId] [int] NOT NULL,
	[AmarCode] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
 