--EXEC [#sp_generate_merge] @schema = 'dbo', @table_name = 'City', @results_to_text = 1, @include_use_db = 0

--MERGE generated by [sp_generate_merge] proc tool. Acknowledgements: https://github.com/dnlnln/generate-sql-merge

SET NOCOUNT ON

DECLARE @mergeOutput TABLE ( [DMLAction] VARCHAR(6) );
MERGE INTO [dbo].[City] WITH (SERIALIZABLE) AS [Target]
USING (VALUES
  (1,N'Abe Bar',0,14,288,NULL,N'1908022262')
 ,(2,N'Ab Pakhsh',0,7,185,NULL,N'1803062308')
 ,(3,N'Abad',0,7,124,NULL,N'1802022816')
 ,(4,N'Abadan',0,13,1,NULL,N'601021270')
 ,(8,N'Abadeh',0,17,2,NULL,N'701041296')
 ,(9,N'Abadeh Tashk',0,17,66,NULL,N'735012199')
 ,(10,N'Abdan',0,7,197,NULL,N'1805032484')
 ,(11,N'Abdanan',0,6,3,NULL,N'1606021501')
 ,(12,N'Abzhdan',0,13,45,NULL,N'621012799')
 ,(13,N'Absard',0,8,191,NULL,N'2302022269')
 ,(14,N'Abesh Ahmad',0,1,343,NULL,N'315032545')
 ,(15,N'Abali',0,8,191,NULL,N'2302032629')
 ,(16,N'Abgarm',0,18,15,NULL,N'2606022517')
 ,(17,N'Abi Biglu',0,3,425,NULL,N'2408012493')
 ,(18,N'Abiz',0,10,232,NULL,N'2909032898')
 ,(19,N'Abik',0,18,4,NULL,N'2604021535')
 ,(20,N'Ajin',0,30,29,NULL,N'1306022758')
 ,(21,N'Azarshahr',0,1,5,NULL,N'321031201')
 ,(22,N'Aradan',0,15,6,NULL,N'2006011549')
 ,(23,N'Arallu',0,3,20,NULL,N'2401042949')
 ,(24,N'Aran va Bidgol',0,4,7,NULL,N'1018021423')
 ,(25,N'Armardeh',0,20,62,NULL,N'1201012457')
 ,(26,N'Arin Shahr',0,10,318,NULL,N'2904052645')
 ,(27,N'Azadshahr',0,24,8,NULL,N'2710021182')
 ,(28,N'Azadi',0,13,46,NULL,N'602022801')
 ,(29,N'Asara',0,5,336,NULL,N'3001032070')
 ,(30,N'Astara',0,25,9,NULL,N'101011117')
 ,(31,N'Astaneh',0,28,269,NULL,N'7011112')
 ,(32,N'Astaneh-ye Ashrafiyeh',0,25,10,NULL,N'102021119')
 ,(33,N'Asmanabad',0,6,146,NULL,N'1604022617')
 ,(34,N'Ashar',0,16,408,NULL,N'1113022893')
 ,(35,N'Ashtian',0,28,11,NULL,N'2011103')
 ,(36,N'Ashkhaneh',0,12,384,NULL,N'2806031352')
 ,(37,N'Aghajari',0,13,12,NULL,N'626011278')
 ,(38,N'Aqqala',0,24,13,NULL,N'2708021180')
 ,(39,N'Aqkand',0,1,413,NULL,N'310022401')
 ,(40,N'Alasht',0,27,260,NULL,N'208021170')
 ,(41,N'Aluni',0,9,153,NULL,N'1410012473')
 ,(42,N'Amol',0,27,14,NULL,N'201021149')
 ,(43,N'Ava',0,12,384,NULL,N'2806012848')
 ,(44,N'Avajiq',0,2,141,NULL,N'414012549')
 ,(45,N'Auj',0,18,15,NULL,N'2606011536')
 ,(46,N'Aveh',0,28,236,NULL,N'6032827')
 ,(47,N'Aysk',0,10,241,NULL,N'2906012346')
 ,(48,N'Abarkuh',0,31,16,NULL,N'2107021293')
 ,(49,N'Abrisham',0,4,310,NULL,N'1008022252')
 ,(50,N'Abu Hamizeh',0,13,184,NULL,N'609022796')
 ,(51,N'Abuzeydabad',0,4,7,NULL,N'1018012279')
 ,(52,N'Abu Musa',0,29,17,NULL,N'2201021563')
 ,(53,N'Abhar',0,14,18,NULL,N'1901031528')
 ,(54,N'Achachi',0,1,413,NULL,N'310042842')
 ,(55,N'Ahmadabad-e Mostowfi',0,8,33,NULL,N'2310032770')
 ,(56,N'Ahmadabad',0,31,22,NULL,N'2101022265')
 ,(57,N'Ahmadabad-e Solt',0,11,116,NULL,N'906042067')
 ,(58,N'Ahmadsargurab',0,25,274,NULL,N'112012387')
 ,(59,N'Arkhiyabad',0,21,338,NULL,N'808052428')
 ,(60,N'Adimi',0,16,434,NULL,N'1115012353')
 ,(61,N'Arak',0,28,19,NULL,N'1021101')
 ,(62,N'Arak 1',2,28,19,NULL,N'1021678')
 ,(63,N'Arak 2',2,28,19,NULL,N'1021679')
 ,(64,N'Arak 3',2,28,19,NULL,N'1021680')
 ,(65,N'Arak 4',2,28,19,NULL,N'1022858')
 ,(66,N'Arak 5',2,28,19,NULL,N'1022859')
 ,(67,N'Arbatan',0,1,439,NULL,N'316012935')
 ,(68,N'Arjomand',0,8,315,NULL,N'2314012634')
 ,(69,N'Ard',0,17,361,NULL,N'727022903')
 ,(70,N'Ardaq',0,18,91,NULL,N'2601062577')
 ,(71,N'Ardabil',0,3,20,NULL,N'2401011195')
 ,(72,N'Ardabil 1',2,3,20,NULL,N'2401011662')
 ,(73,N'Ardabil 2',2,3,20,NULL,N'2401011663')
 ,(74,N'Ardabil 3',2,3,20,NULL,N'2401012575')
 ,(75,N'Ardabil 4',2,3,20,NULL,N'2401012852')
 ,(76,N'Ardabil 5',2,3,20,NULL,N'2401012873')
 ,(77,N'Ordistan',0,4,21,NULL,N'1001011395')
 ,(78,N'Ardakan',0,17,238,NULL,N'706021304')
 ,(79,N'Ardakan',0,31,22,NULL,N'2101021551')
 ,(80,N'Ardal',0,9,23,NULL,N'1405011476')
 ,(81,N'Ardimusi',0,3,249,NULL,N'2410022881')
 ,(82,N'Orzuiyeh',0,21,24,NULL,N'823012315')
 ,(83,N'arsak',0,10,76,NULL,N'2908022726')
 ,(84,N'Arsanjan',0,17,25,NULL,N'717011321')
 ,(85,N'Arteh',0,27,317,NULL,N'210022747')
 ,(86,N'Arkuaz',0,6,400,NULL,N'1608011508')
 ,(87,N'Armaghankhaneh',0,14,230,NULL,N'1904062038')
 ,(88,N'Urmia',0,2,26,NULL,N'401041235')
 ,(89,N'Urmia 5',2,2,26,NULL,N'401042853')
 ,(90,N'Urmia 1',2,2,26,NULL,N'401042528')
 ,(91,N'Urmia 2',2,2,26,NULL,N'401042529')
 ,(92,N'Urmia 3',2,2,26,NULL,N'401042530')
 ,(93,N'Urmia 4',2,2,26,NULL,N'401042531')
 ,(94,N'Arvand Kenar',0,13,1,NULL,N'601011269')
 ,(95,N'Azgaleh',0,22,128,NULL,N'512022593')
 ,(96,N'Azna',0,26,27,NULL,N'1507021488')
 ,(97,N'Azandarian',0,30,398,NULL,N'1302012253')
 ,(98,N'Ezhiyeh',0,4,37,NULL,N'1002062248')
 ,(99,N'Asalem',0,25,291,NULL,N'104052382')
 ,(100,N'Espakeh',0,16,433,NULL,N'1107042506')
) AS [Source] ([Id],[Name],[CityType],[ProvinceId],[CountyId],[DistrictId],[AmarCode])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND EXISTS (SELECT [Source].[Name], [Source].[CityType], [Source].[ProvinceId], [Source].[CountyId], [Source].[DistrictId], [Source].[AmarCode]
                 EXCEPT  SELECT [Target].[Name], [Target].[CityType], [Target].[ProvinceId], [Target].[CountyId], [Target].[DistrictId], [Target].[AmarCode]) THEN
 UPDATE SET
  [Target].[Name] = [Source].[Name], 
  [Target].[CityType] = [Source].[CityType], 
  [Target].[ProvinceId] = [Source].[ProvinceId], 
  [Target].[CountyId] = [Source].[CountyId], 
  [Target].[DistrictId] = [Source].[DistrictId], 
  [Target].[AmarCode] = [Source].[AmarCode]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Name],[CityType],[ProvinceId],[CountyId],[DistrictId],[AmarCode])
 VALUES([Source].[Id],[Source].[Name],[Source].[CityType],[Source].[ProvinceId],[Source].[CountyId],[Source].[DistrictId],[Source].[AmarCode])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
OUTPUT $action INTO @mergeOutput;

DECLARE @mergeError INT = @@ERROR, @mergeCount INT = (SELECT COUNT(1) FROM @mergeOutput), @mergeCountIns INT = (SELECT COUNT(1) FROM @mergeOutput WHERE [DMLAction] = 'INSERT'), @mergeCountUpd INT = (SELECT COUNT(1) FROM @mergeOutput WHERE [DMLAction] = 'UPDATE'), @mergeCountDel INT = (SELECT COUNT(1) FROM @mergeOutput WHERE [DMLAction] = 'DELETE');
IF @mergeError <> 0 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[City]' + CONCAT(' (SQL Server error code: ', @mergeError) + ')';
PRINT CONCAT('[dbo].[City] rows affected by MERGE: ', @mergeCount) + CONCAT(' (Inserted: ', @mergeCountIns) + CONCAT('; Updated: ', @mergeCountUpd) + CONCAT('; Deleted: ', @mergeCountDel) + ')';
GO


SET NOCOUNT OFF
GO


