
USE [master]
GO

/****** Object:  Database [DamKhatoonDb]    Script Date: 6/10/2026 5:40:17 AM ******/
CREATE DATABASE [DamKhatoonDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DamKhatoonDb', FILENAME = N'E:\flutter\khatoon_application\khatoon_database\DamKhatoonDb.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DamKhatoonDb_log', FILENAME = N'E:\flutter\khatoon_application\khatoon_database\DamKhatoonDb_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [DamKhatoonDb] SET COMPATIBILITY_LEVEL = 170
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DamKhatoonDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DamKhatoonDb] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ANSI_NULLS OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ANSI_PADDING OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ARITHABORT OFF
GO

ALTER DATABASE [DamKhatoonDb] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [DamKhatoonDb] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [DamKhatoonDb] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [DamKhatoonDb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [DamKhatoonDb] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [DamKhatoonDb] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [DamKhatoonDb] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [DamKhatoonDb] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [DamKhatoonDb] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [DamKhatoonDb] SET  DISABLE_BROKER
GO

ALTER DATABASE [DamKhatoonDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [DamKhatoonDb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [DamKhatoonDb] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [DamKhatoonDb] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [DamKhatoonDb] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [DamKhatoonDb] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [DamKhatoonDb] SET RECOVERY SIMPLE
GO

ALTER DATABASE [DamKhatoonDb] SET  MULTI_USER
GO

ALTER DATABASE [DamKhatoonDb] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [DamKhatoonDb] SET DB_CHAINING OFF
GO

ALTER DATABASE [DamKhatoonDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [DamKhatoonDb] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [DamKhatoonDb] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [DamKhatoonDb] SET OPTIMIZED_LOCKING = OFF
GO

ALTER DATABASE [DamKhatoonDb] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [DamKhatoonDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [DamKhatoonDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DamKhatoonDb] SET  READ_WRITE
GO
